## Numpy

In [1]:
# Câu 1: 
import numpy as np
from scipy import stats
#Tạo numpy array từ 0 đến 10
arr = np.arange(11)
# Xem kiểu dữ liệu của mảng và kiểu dữ liệu phần tử của mảng
print("Kieu du lieu cua mang: ", type(arr))
print("Kieu du lieu cua phan tu trong mang:", arr.dtype)
# Xem kích thước của mảng
print("Kich thuoc cua mang:", arr.shape)

Kieu du lieu cua mang:  <class 'numpy.ndarray'>
Kieu du lieu cua phan tu trong mang: int64
Kich thuoc cua mang: (11,)


In [3]:
# Câu2
# Thực hiện sắp xếp mảng vừa tạo ở câu 1 theo thứ tự giảm dần
arr_sorted = np.sort(arr)[::-1]
print(arr_sorted)
# Từ mảng vừa tạo, tạo 2 mảng con có giá trị lần lượt là lớn hơn 6 (>6) và bé hơn 6 (<6)
a=arr>6
arr1=arr[a]
print(arr1)
b=arr<6
arr2=arr[b]
print(arr2)

[10  9  8  7  6  5  4  3  2  1  0]
[ 7  8  9 10]
[0 1 2 3 4 5]


In [4]:
#Câu 3
# Thêm [11,12] vào cuối mảng vừa tạo ở câu 1
new_arr=[11,12]
arr=np.append(arr,new_arr)
print(arr)
# Thêm giá trị 100 vào mảng trên tại vị trí có index là 5
new_arr1=np.insert(arr,5,100)
print(new_arr1)
# Xoa phan tu co index lan luot la 5,11,12
arr = np.delete(arr,[5,11,12])
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[  0   1   2   3   4 100   5   6   7   8   9  10  11  12]
[ 0  1  2  3  4  6  7  8  9 10]


In [5]:
#Câu 4: 
# Tao mot mang numpy voi cac gia tri ngau nhien (int) tu 1 den 100, kich thuoc 20
arr_rand = np.random.randint(1,100,20)
print(arr_rand)
# Tinh tong, trung binh, phuong sai, do lech chuan, trung vi, yeu tri, gia tri lon nhat, gia tri nho nhat cua mang do
arr_sum = np.sum(arr_rand) #tong
arr_mean = np.mean(arr_rand) #trung binh
arr_variance = np.var(arr_rand)
arr_std = np.std(arr_rand) #do lech chuan
arr_median = np.median(arr_rand) #trungvi
arr_mode_result = stats.mode(arr_rand) #yeu tri
arr_max = np.max(arr_rand)# gia tri lon nhat
arr_min = np.min(arr_rand)# gia tri nho nhat
print(f"Tổng: {arr_sum}\nTrung bình: {arr_mean}\nPhương sai: {arr_variance}\nĐộ lệch chuẩn: {arr_std}\nTrung vi: {arr_median}\nYếu trị: {arr_mode_result.mode}\nGiá trị lớn nhất: {arr_max}\nGiá trị nhỏ nhất: {arr_min}")


[31 82 84 17 74 86 10 93 41 83 57 71 14 87 37 31 99 73 40  3]
Tổng: 1113
Trung bình: 55.65
Phương sai: 920.3275
Độ lệch chuẩn: 30.336899973464657
Trung vi: 64.0
Yếu trị: 31
Giá trị lớn nhất: 99
Giá trị nhỏ nhất: 3


In [6]:
#Câu 5:
# Tạo một ma trận 3x3 với các giá trị từ 1 đến 9 và cộng thêm một giá trị scalar bằng 10 vào từng phần tử
arr3 = np.random.randint(1,9,size=(3,3))
# Tạo hai mảng np.array([1, 2, 3, 4]) và np.array([5, 6, 7, 8]) với kích thước 4 và thực hiện phép nhân ma trận.
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])
result = np.dot(A,B)
# Tạo một ma trận 5x5 với các giá trị ngẫu nhiên từ 1 đến 100 và chuẩn hóa giá trị trong ma trận để nằm trong khoảng [0, 1].
arr5 = np.random.randint(1,100,size=(5,5))
arr5 = (arr5-np.min(arr5))/(np.max(arr5)-np.min(arr5))
print(arr5)

[[0.01333333 0.14666667 0.52       0.25333333 1.        ]
 [0.18666667 0.6        0.98666667 0.48       0.        ]
 [0.21333333 0.33333333 0.44       0.37333333 0.54666667]
 [0.61333333 0.21333333 0.65333333 0.02666667 0.01333333]
 [0.44       0.96       0.62666667 0.74666667 0.41333333]]


In [6]:
# Câu 6
# Giải hệ phương trình tuyến tính dựa vào ma trận nghịch đảo
# 2a-b-c = 4
# 3a + 4b -2c = 11
# 3a-2y+4z = 11
# Trong đó:
# Định thức được tính dựa vào hàm : np.linalg.det(matrix)
# Ma trận nghịch đảo dựa vào hàm : np.linalg.inv(matrix)
# Nhân hai ma trận dùng hàm sau: np.dot(matrix)

## Pandas

In [7]:
# 1. Đọc file dữ liệu

# Đưa ra các thống kê mô tả cơ bản cho các cột số

In [8]:
#2 Thay đổi tên của các cột sau col --> cholesterol , thal --> thalassemia

In [9]:
#3
# Xoá các dòng bị trùng lặp

# Xóa các dòng trùng lặp và giữ lại dòng đầu tiên

In [10]:
# Câu 4
# Kiểm tra các giá trị null có trong mỗi cột và xử lý các giá trị null đó

In [11]:
# Tính giá trị trung bình của cột 'age'

# Thay thế giá trị NaN trong cột 'age' bằng giá trị trung bình


In [12]:
# Câu 5 
# In ra các dòng có age > 60

# Thêm dòng dữ liệu mới

# Tạo cột mới có tên là outcome với giá trị [Có; Không] nếu Target là 1 --> Có; 0 --> Không


# Xoá cột cp

# Xoá dòng có giá trị age bằng 37

# Sắp xếp giá trị cột age theo giá trị giảm dần

# Người có độ tuổi lớn nhất và bé nhất

In [13]:
# Câu 6: Xuất file dữ liệu

## Matplotlib

In [14]:
import matplotlib.pyplot as plt
import numpy as np

In [15]:
# Câu 1: Khởi tạo 2 mảng ngẫu nhiên X, Y có kích thươc là (50,)
# Vẽ biểu đồ scatter với tên là "Biểu đồ biểu diễn sự phân tán"
# Marker màu đó có kích thước là 100

In [16]:
# Câu 2: Khởi tạo một mảng ngẫu nhiên Z có kích thước là (1000,). 
# Vẽ biểu đồ histogram để biểu diễn phân phối của Z. Sử dụng 30 bins, màu sắc của histogram là màu xanh dương, và thêm lưới vào biểu đồ. 
# Tiêu đề của biểu đồ là "Biểu đồ phân phối của Z".

In [17]:
# Câu 3: Khởi tạo một mảng ngẫu nhiên thời gian T có kích thước (12,) để đại diện cho 12 tháng trong năm và 
# một mảng ngẫu nhiên S với cùng kích thước để đại diện cho doanh số bán hàng. 
# Vẽ biểu đồ đường với S là giá trị theo thời gian T. Đặt tên cho biểu đồ là "Biểu đồ đường doanh số theo tháng". 
# Đường màu xanh lá cây, marker là hình vuông với kích thước 8.

In [18]:
# Câu 4: Khởi tạo một mảng ngẫu nhiên A với 5 giá trị đại diện cho các loại sản phẩm, 
# và một mảng ngẫu nhiên B với 5 giá trị đại diện cho doanh số của từng loại sản phẩm. 
# Vẽ biểu đồ cột để biểu diễn doanh số của các sản phẩm với tên biểu đồ là "Doanh số các loại sản phẩm". 
# Mỗi cột có màu vàng và hiển thị giá trị trên mỗi cột.

In [19]:
# Câu 5: Khởi tạo 3 mảng ngẫu nhiên M1, M2, và M3 có kích thước là (100,). 
# Vẽ biểu đồ boxplot để biểu diễn phân phối của ba nhóm dữ liệu này. Đặt tên biểu đồ là "Biểu đồ hộp của ba nhóm dữ liệu". 
# Sử dụng màu xanh lam cho hộp và màu đỏ cho đường trung vị.

In [20]:
# Câu 6: Khởi tạo một mảng ngẫu nhiên P với 5 giá trị đại diện cho tỷ lệ phần trăm của 5 loại dịch vụ. 
# Vẽ biểu đồ pie chart để biểu diễn tỷ lệ phần trăm của các loại dịch vụ này.
#  Đặt tên biểu đồ là "Biểu đồ tỷ lệ phần trăm của các loại dịch vụ". Mỗi phần của biểu đồ có màu khác nhau, 
# và phần có giá trị lớn nhất được tách ra (explode). Thêm nhãn giá trị phần trăm vào từng phần.